---
date: "2021-09-12T15:26:15Z"
draft: false
title: 1950s - Today
weight: 30
bibliography: references.bib
---

## Functions of Industrial Engineering and Operations Research Professionals

As the 70s and 80s approached, some talks claimed that industrial engineering was
losing its identity with more quantitative techniques and computers being 
introduced. Yet the differences between industrial engineering and operations 
research couldn't get any more distinct [@holsten_1999]. If we were to look at 
the BLS and compare occupations:

---

**Industrial Engineers**

"Industrial engineers devise efficient systems that integrate workers, machines, 
materials, information, and energy to make a product or provide a service."

**Operations Research Analyst**

"Operations research analysts use advanced mathematical and analytical methods 
to help solve complex issues."

---

Industrial engineering is more domain-focused (manufacturing in particular) on 
**optimizing processes, ergonomics, design, material handling,** and more [@maynard_zandin_2001]. 
Operations research focuses on **how to optimize** resources at hand to achieve 
an organizational goal. You'll see the skillsets of industrial engineers involve 
quality control, improving production flow, and time/cost reduction. While 
operations research analysts are involved in some of those processes, they are 
not normally the key decision makers despite helping in that 
decision-making process.

## References